# baseURL = '/'
title = 'SubNetworks'
theme = "OnzeTheme" 

languageCode = 'en-us'
DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1