baseURL = 'http://example.org/'
title = 'SubNetworks'
theme = "OnzeTheme" 

languageCode = 'en-us'
DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
